export const products: any = [
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    },
    {
        id: 1,
        name: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        description: "Album Cán Màng Ruột Siêu Sắc Nét 4K",
        price: "129000",
        rating: 5.0,
        status: "Đang bán",
        reviews: 345,
        colors: ["Đen", "Trắng", "Silver", "Gold"],
        material: ["Bìa Gói", "Bìa Kính", "Bìa Da"],
        images: [
            "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996916/iatt/IMG_7668_tevby4.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996855/iatt/IMG_7669_mbjo7j.jpg",
            "https://res.cloudinary.com/farmcode/image/upload/v1728996259/iatt/IMG_7660_e9bgmw.jpg",
        ],
    }
];

export const other_services: any = [
    {
        image: "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
        title: "SÁCH ẢNH - ALBUM PHOTOBOOK",
    },
    {
        image: "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
        title: "IN ẢNH - TỰ THIẾT KẾ",
    },
    {
        image: "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
        title: "TRANG TRÍ NHÀ - VĂN PHÒNG",
    },
    {
        image: "https://res.cloudinary.com/farmcode/image/upload/v1728997182/iatt/IMG_7675_zqrn92.jpg",
        title: "LỊCH - CALENDAR",
    },
];